### ISSUE TITLE
已强制推送的状态下如何恢复远程仓库文件

### ISSUE THREAD

**Issue by Light--** [fengerzh/fengerzh.github.io#2]
# Bug Report

**Describe the bug**
张总您好！
我是个git小白，犯了一个强制推送 push -f引起的错误，查阅到您的大作：https://www.fengerzh.com/git-reset/ 之后想请教一下：

在文中提到的“已推送(Pushed)”状态下，如果本地仓库和远程仓库不等价，想要恢复远程仓库的文件，还能恢复得出来吗？

**To Reproduce**
1，在github网页端建立了一个远程仓库repo，手动在网页端创建了A.file文件，写入了一些内容。
2，本地有一个文件夹folder包含B.file文件**（不包含A.file文件）**。原本是想将本地的B文件提交到远程仓库，和A共存。但我操作错了，我的操作是：
```
$ cd folder
$ git init // 将本地的文件夹用```git init```初始化为git目录
$ git add B.file   
$ git commit -m "upload B"   
$ git remote add origin git@github.com:Light--/repo.git  
$ git push -u origin master -f // 强制push
```
3，然后就发现远程仓库repo下的A.file文件不见了，只有个B.file文件。。。。

**Expected behavior**

提交B.file到远程仓库repo下，从而远程仓库repo下有A.file和B.file两个文件

**Desktop (please complete the following information):**

- OS:  macos
- Browser chrome
- Version 

**Additional context**
我知道我的操作可能在您看来简直是瞎折腾，但还是抱着一丝希望想请教一下，这种情况下，远程仓库中的A.file还能恢复出来么。。网上的好多教程都是基于本地仓库和远程仓库等价的条件下。

**Comment by fengerzh** [comment]
还是要看历史，如果历史中有的话，就可以找回来，如果历史中没有，那就找不回来了。

**Comment by Light--** [comment]
> 还是要看历史，如果历史中有的话，就可以找回来，如果历史中没有，那就找不回来了。

谢谢您的回复，我是在您的博客上提交不了私信才上这里求教的。
我用```git reflog```能看到历史，但是也只是本地的历史，有什么方法可以查看远端的历史，然后对远端的修改进行回退吗？

**Comment by fengerzh** [comment]
要看你远端用的是什么服务器，如果是gitlab或phabricator的话都有相应的web页面可供查看，其他的服务器不清楚。

**Comment by Light--** [comment]
> 要看你远端用的是什么服务器，如果是gitlab或phabricator的话都有相应的web页面可供查看，其他的服务器不清楚。

远端就是咱们现在所在的这个github.com
好吧。。谢谢！
